[git_commit_and_push_all] various updates

diff --git a/dotfiles/bin/git-ci-logs b/dotfiles/bin/git-ci-logs
--- a/dotfiles/bin/git-ci-logs
+++ b/dotfiles/bin/git-ci-logs
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 ################################################################### SETUP ########################################################################
+if ! _SCRIPT_DIR="$(get_script_dir "${BASH_SOURCE[0]}")"; then echo "Error while running: _SCRIPT_DIR=\"\$(get_script_dir \"${BASH_SOURCE[0]}\")\"" && exit 1; fi
+# shellcheck source=./.common_copy.sh
+source "${_SCRIPT_DIR}/.common_copy.sh" || exit 1
 set -o errexit -o errtrace -o nounset
 ##################################################################################################################################################
 
@@ -10,5 +13,5 @@ api_url="$(git ci-last-url-shortcut "$@")/consoleText"
 if check_debug; then
   echo jenkins_curl "$api_url"
 else
-  jenkins_curl "$api_url"
+  log_and_run jenkins_curl "$api_url"
 fi
