[git_commit_and_push_all] various updates

diff --git a/dotfiles/bin/git-ci-tail b/dotfiles/bin/git-ci-tail
--- a/dotfiles/bin/git-ci-tail
+++ b/dotfiles/bin/git-ci-tail
@@ -1,14 +1,12 @@
 #!/usr/bin/env bash
 ################################################################### SETUP ########################################################################
+if ! _SCRIPT_DIR="$(get_script_dir "${BASH_SOURCE[0]}")"; then echo "Error while running: _SCRIPT_DIR=\"\$(get_script_dir \"${BASH_SOURCE[0]}\")\"" && exit 1; fi
+# shellcheck source=./.common_copy.sh
+source "${_SCRIPT_DIR}/.common_copy.sh" || exit 1
 set -o errexit -o errtrace -o nounset
 ##################################################################################################################################################
 
 git check-supported-ci-types jenkins
 
 api_url="$(git ci-last-url "$@")"
-
-if check_debug; then
-  echo jenkins_tail "$api_url"
-else
-  jenkins_tail "$api_url"
-fi
+log_and_run jenkins_tail "$api_url"
